CREATE LOGIN Борис WITH PASSWORD = 'Boris123!';
CREATE LOGIN Александр WITH PASSWORD = 'Alex123!';
CREATE LOGIN Алексей WITH PASSWORD = 'Aleksey123!';
CREATE LOGIN Ольга WITH PASSWORD = 'Olga123!';
CREATE LOGIN Елена WITH PASSWORD = 'Elena123!';
GO
ALTER SERVER ROLE sysadmin ADD MEMBER Борис;
ALTER SERVER ROLE sysadmin ADD MEMBER Александр;
ALTER SERVER ROLE sysadmin ADD MEMBER Алексей;
ALTER SERVER ROLE sysadmin ADD MEMBER Ольга;
ALTER SERVER ROLE sysadmin ADD MEMBER Елена;
GO